### ISSUE TITLE
Unit creation

### ISSUE THREAD

**Issue by xR3b0rn** [pongstylin/tactics#10]
I'm programming on my own tactics since a few years in C++. I did a lot of thinking and work, how to use the images. Because I read, adobe is smartly loading and unloading images so the RAM isn't exploding and I didn't want to write my own image loader and unloader, I decided to use spritesheets. I exported all informations about the animations out of the orginal .swf files, so I got the spritesheets and the coordinate vectors of those. With this you will be able to write your own unit animation parser so you wont have to write a animation file for each unit by your self. This saves a lot of work and makes handling the images much more easy and saves a bit of overhead performance.

But here is an example:
The image:
https://i.imgur.com/8Pg9oHA.png
And the corresponding vectors for this image:
```
(function(window) {
sprite_3418_(Ambusher) = function() {
	this.initialize();
}
sprite_3418_(Ambusher)._SpriteSheet = new SpriteSheet({images: ["ambusher_normal.png"], frames: [[0,0,82,57,0,41,43.95],[0,0,82,57,0,41,43.95],[82,0,54,60,0,29,50.95],[136,0,65,63,0,42,53.95],[201,0,69,64,0,48,55.95],[270,0,66,63,0,50,57.95],[270,0,66,63,0,50,57.95],[336,0,52,61,0,50,64.95],[270,0,66,63,0,50,57.95],[201,0,69,64,0,48,55.95],[136,0,65,63,0,42,53.95],[82,0,54,60,0,29,50.95],[388,0,55,66,0,27,48.95],[443,0,58,67,0,25,47.95],[0,67,50,67,0,17,44.95],[336,0,52,61,0,6,36.95],[270,0,66,63,0,6,29.950000000000003],[50,67,69,64,0,4,27.950000000000003],[136,0,65,63,0,-2,25.950000000000003],[82,0,54,60,0,-15,22.950000000000003],[82,0,54,60,0,-15,22.950000000000003],[119,67,80,57,0,45,43.95],[199,67,82,61,0,50,46.95],[281,67,91,63,0,60,49.95],[372,67,118,80,0,71,65.95],[0,147,74,97,0,32,83.95],[74,147,76,68,0,30,53.95],[150,147,67,71,0,31,54.95],[217,147,65,63,0,31,47.95],[282,147,78,57,0,36,43.95],[282,147,78,57,0,36,43.95],[217,147,65,63,0,31,47.95],[360,147,40,64,0,19,45.95],[400,147,52,61,0,25,50.95],[452,147,50,66,0,12,58.95],[0,244,58,67,0,12,61.95],[58,244,57,66,0,7,62.95],[58,244,57,66,0,7,62.95],[115,244,54,61,0,5,64.95],[58,244,57,66,0,7,62.95],[0,244,58,67,0,12,61.95],[452,147,50,66,0,12,58.95],[400,147,52,61,0,25,50.95],[169,244,66,62,0,39,43.95],[235,244,69,65,0,44,41.95],[304,244,66,63,0,47,39.95],[115,244,54,61,0,49,36.95],[58,244,57,66,0,51,34.95],[370,244,58,67,0,56,33.95],[452,147,50,66,0,56,30.950000000000003],[400,147,52,61,0,69,22.950000000000003],[400,147,52,61,0,69,22.950000000000003],[428,244,49,65,0,27,46.95],[0,311,60,67,0,31,47.95],[60,311,71,65,0,30,46.95],[131,311,74,95,0,19,75.95],[205,311,70,112,0,36,91.95],[275,311,70,63,0,40,41.95],[345,311,75,57,0,42,37.95],[420,311,75,59,0,42,40.95],[0,423,47,64,0,25,45.95],[0,423,47,64,0,25,45.95],[420,311,75,59,0,42,40.95],[47,423,82,61,0,42,45.95],[129,423,54,64,0,26,52.95],[183,423,65,71,0,24,48.95],[248,423,70,72,0,22,47.95],[318,423,66,74,0,17,44.95],[318,423,66,74,0,17,44.95],[384,423,52,73,0,3,39.95],[318,423,66,74,0,17,44.95],[248,423,70,72,0,22,47.95],[183,423,65,71,0,24,48.95],[129,423,54,64,0,26,52.95],[436,423,56,67,0,29,57.95],[0,497,57,69,0,34,59.95],[57,497,51,67,0,34,61.95],[108,497,52,74,0,47,67.95],[160,497,66,75,0,61,72.95],[248,423,70,72,0,66,75.95],[183,423,65,71,0,68,76.95],[129,423,54,64,0,70,80.95],[129,423,54,64,0,70,80.95],[226,497,78,60,0,35,44.95],[304,497,82,67,0,33,45.95],[386,497,91,80,0,32,51.95],[0,577,118,61,0,48,43.95],[118,577,75,114,0,43,104.95],[193,577,77,59,0,47,52.95],[270,577,67,61,0,37,52.95],[337,577,65,62,0,35,50.95],[402,577,78,62,0,43,46.95],[402,577,78,62,0,43,46.95],[337,577,65,62,0,35,50.95],[0,691,40,70,0,22,48.95],[40,691,52,72,0,28,52.95],[92,691,51,67,0,39,47.95],[143,691,58,69,0,47,45.95],[201,691,56,68,0,50,43.95],[201,691,56,68,0,50,43.95],[257,691,54,65,0,50,39.95],[201,691,56,68,0,50,43.95],[143,691,58,69,0,47,45.95],[92,691,51,67,0,39,47.95],[40,691,52,72,0,28,52.95],[311,691,65,73,0,27,58.95],[376,691,69,72,0,26,61.95],[445,691,66,71,0,20,63.95],[257,691,54,65,0,6,67.95],[201,691,56,68,0,6,71.95],[143,691,58,69,0,3,73.95],[92,691,51,67,0,-5,75.95],[40,691,52,72,0,-16,80.95],[40,691,52,72,0,-16,80.95],[0,764,49,71,0,23,48.95],[49,764,61,83,0,31,49.95],[110,764,71,95,0,42,55.95],[181,764,74,92,0,56,64.95],[255,764,70,114,0,35,95.95],[325,764,69,61,0,30,52.95],[394,764,75,68,0,34,51.95],[0,878,75,68,0,34,48.95],[75,878,47,70,0,23,48.95],[75,878,47,70,0,23,48.95],[0,878,75,68,0,34,48.95]]});
var sprite_3418_(Ambusher)_p = sprite_3418_(Ambusher).prototype = new BitmapAnimation();
sprite_3418_(Ambusher)_p.BitmapAnimation_initialize = sprite_3418_(Ambusher)_p.initialize;
sprite_3418_(Ambusher)_p.initialize = function() {
	this.BitmapAnimation_initialize(sprite_3418_(Ambusher)._SpriteSheet);
	this.paused = false;
}
window.sprite_3418_(Ambusher) = sprite_3418_(Ambusher);
}(window));

```

Let me know if you are interested.

Btw. it's also possible to export .swf movies and embed them into HTML to play them.

PS. I'm coming from the C++ corner, what means I have to learn some things about web development and Javascript. But I will make some contributions in the future to this project. I'm really happy that I found this project.

**Comment by Enijar** [comment]
Great work. I see a couple of issues with the sprite sheet you have created

1. There are no shadows
2. How do you add colour to the unit? Each unit needs to be coloured. In the original source code there are essentially three layers (shadow, colour, and base)

Regarding exporting assets from the SWF game file, you can see [this](https://github.com/pongstylin/tactics/issues/1#issuecomment-436066831) comment in [issue#1](https://github.com/pongstylin/tactics/issues/1) for a full HTML5 canvas export of all units. @pongstylin has worked on an extraction tool to create a JSON file for each unit, describing it's animation, [Here is an example of the Cleric](https://github.com/pongstylin/tactics/blob/extract_unit_data/static/extract/extracted/cleric.json).

Since you're from a C++ background, you may want to take a look into [Web Assembly](https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm). You code in C++ and convert that to code readable by the browser.

**Comment by pongstylin** [comment]
We have a super long thread talking about automating the extraction of units from the SWF under the "More Units" issue. In fact, the "extract_unit_data" branch contains code to that end.  We have had a lot of success, but that doesn't mean I'm not interested. I would like to contrast your approach with ours and see where the advantages lie. I care about a lot of things from download size and memory usage to accuracy and ease of integration.  There are sacrifices I'm willing to make in the short term in the name of progress that we might overhaul in the long term in the name of science.

So, I want to explore your approach and see what I might learn so that decisions can be made. At the same time, I invite you to explore what we have done so that you know our context and can help with that contrast analysis.

I'm about to travel today for the holiday, so I will leave you questions for now.
1) Do I understand correctly that you have a relatively automated mechanism to generate spreadsheets and frame data for any unit?
2) Have you had success with integrating shadows with the unit? (They are extracted separately from the SWF, in my experience.)
3) Have you had success positioning any unit on a game board tile?
4) Have you had success animating units with non-image effects, such as the orange assassin explosion or white lightning ward glow?
5) Have you had success extracting animations complete with sound?

**Comment by xR3b0rn** [comment]
You have three sprite sheets per Unit. I named them shadow, color and normal. If you want to animate them, you have to put each frame on top of the other.

**Comment by pongstylin** [comment]
I arrived at my destination. Haven't reviewed your code yet, but I have a second round of questions.
1) Would it require a lot of work to demonstrate animating a unit on a webpage? Perhaps the assassin? No need for parsing the individual animations or applying sounds - just layering and animating all of the frames.
2) To explain "non-image effects", look at @Enijar's comment in "More Units" issue for the assassin. When it performs the assassin bomb animation, you will see an orange explosion. The explosion is drawn with code. It is not an image. I'm curious if your technique includes "Special Effects" like this. If not with the unit, perhaps separately. @Enijar's comment also includes a page called "Glow". It is another "Special Effect" (no images) used by the Lightning Ward before it sends a lightning bolt.
3) How are the units positioned? For example, I might have a frame with 3 sprites accurately layered inside. I also have a tile frame on a game board.  So far, I have not found a general formula for positioning the unit frame such that the feet are in the center of the tile frame. I expect that the SWF data must provide an anchor point (e.g. x:45, y:67) for each frame so that you can position it relative to an anchor point of a tile, e.g. the center or top of the tile.
4) We are also in a place where we manually enter the individual animation frame offsets and which sounds to play when. I'm currently fiddling with the assassin block animation sound. Most of the sounds are pretty easy, but this one is kicking my butt. Surely there is a way to get this information from the SWF. Even if not automated, a reference would be better than trial and error.

**Comment by Enijar** [comment]
@pongstylin I can get the audio files out of the SWF for you. I though you already had them extracted?

**Comment by pongstylin** [comment]
@Enijar
I think I have all the audio files. But I'm having trouble selecting and timing the right one for the assassin block sound.

**Comment by Enijar** [comment]
@Enijar I see. I'll have a look through the exported dump of data from the [JPEX tool](https://github.com/jindrapetrik/jpexs-decompiler) when I'm back home from work. Maybe there is more data to make use of from the exporter.

**Comment by xR3b0rn** [comment]
2. My method also extracts the bomb, because it is working direktly on the animation.

3. You set the x and y position in the center (I basically worked only with centered coordinates) of a tile, all coordinates in the vector are relative to those.

4. I also extracted the audio files out of the fla.

Here the assassin normal image:
https://imgur.com/a/JXviizf

**Comment by Enijar** [comment]
@xR3b0rn Can you make your project public?

**Comment by xR3b0rn** [comment]
My problem are the leaked datas which are part of my project. I'm not sure whether this is legal... I will try to put anything on a git without the digisonline data and the make my source public.

**Comment by Enijar** [comment]
@xR3b0rn  Can you make a new repo and strip out all "private data"?

**Comment by xR3b0rn** [comment]
https://git.julian-prog.de/root/tactics_empty.git

Basically it should run on Linux and Windows (if it's in a runable state, I don't know, because I started to work on a new version).
If you are cmaking on Linux it should be no problem but on windows it's a bit hard, because you have to provice each dependency. (There are some e.g. libarchive, sfml, boost)

I tryed to keep the mvc model, may be a bit too sirious.

And there is a project called Animation Container Creator, which shall hold all the data needed to animate the units in one file, e.g. furgon.animationcreator (serialization and deserialization of the data is part of the project). For now this program is handling all 3 images, the offset vectors of those, sounds and frame ranges by parsing the .js file and putting it all together in one file - may be it would be usefull for the project as well.

**Comment by xR3b0rn** [comment]
unlisted.

**Comment by pongstylin** [comment]
I just had a thought.  With a spritesheet, you need data that describes the location and dimensions of each sprite.  But with Data URLs, you don't need that.  You could say that the current JSON format illustrates the minimal data already.  That is, each sprite has an anchor.x and anchor.y and the overall frame anchor should be something consistent from unit to unit, which isn't the case right now, but could be.  Let me know if that doesn't make sense.

**Comment by xR3b0rn** [comment]
I made a example now. It is working javascript:

[extract.zip](https://github.com/pongstylin/tactics/files/2612297/extract.zip)

**Comment by xR3b0rn** [comment]
Also did this with wispet. (Wispet also "programmed" the white fog on the wispet) But this is no problem with Spritesheets:
[wispet.zip](https://github.com/pongstylin/tactics/files/2612354/wispet.zip)

**Comment by xR3b0rn** [comment]
If you agree and give me some instructions howto integrate, I would integrate each unit with this method.

**Comment by xR3b0rn** [comment]
Do you have to generate the json files by your self?

**Comment by pongstylin** [comment]
I generated the JSON file like this:
```bash
cd tactics
git checkout extract_unit_data
cd static/extract/
node extract.js sources/ambusher.html sources/ambusher_shadow.html
```

JSON and JS files are written to the "extracted" directory.  My script generated the JSON files, but the Data URLs/PNG images were not generated by my "extract.js" script.  They came from the source HTML files that were generated by @Enijar from the SWF using an open source Java tool.

**Comment by pongstylin** [comment]
By the way, are you in the TAO facebook group?  I invite you to send me messages on Facebook Messenger to ask me all the questions you like.

**Comment by xR3b0rn** [comment]
I do not have facebook. :(

**Comment by Enijar** [comment]
@pongstylin @xR3b0rn Shall we make a Discord channel to discuss more quickly in? Github issues isn't the best place for extended discussion.

**Comment by xR3b0rn** [comment]
You thinked of an irc channel

**Comment by pongstylin** [comment]
I'm also a slacker.  Do you guys use Slack?

**Comment by xR3b0rn** [comment]
@Enijar yes, sounds good.

**Comment by Enijar** [comment]
@pongstylin you have to pay for Slack, that's my only concern. I can invite you guys to the Discord server in a sec

**Comment by xR3b0rn** [comment]
https://discord.gg/bYu7mx

**Comment by Enijar** [comment]
Join the server through [this link](https://discord.gg/JXbg8D)

**Comment by pongstylin** [comment]
Slack has a free tier, but I don't mind discord.

**Comment by xR3b0rn** [comment]
Or an simple irc channel?

**Comment by xR3b0rn** [comment]
Here all three images of the ambusher optimized with https://pngquant.org/:
![ambusher_normal-fs8](https://user-images.githubusercontent.com/6249046/49024416-b4c68700-f199-11e8-9b40-29e8e1f256e9.png)
![ambusher_shadow-fs8](https://user-images.githubusercontent.com/6249046/49024418-b55f1d80-f199-11e8-8699-df590e9e4ec1.png)
![ambusher_color-fs8](https://user-images.githubusercontent.com/6249046/49024419-b55f1d80-f199-11e8-812a-426c41b44d0c.png)

**Comment by xR3b0rn** [comment]
8bit, cutting and stacking: (98,2Kb)
![ambusher_color_min-fs8](https://user-images.githubusercontent.com/6249046/49036133-25c86780-f1b7-11e8-8d7d-646033eed8b3.png)
![ambusher_normal_min-fs8](https://user-images.githubusercontent.com/6249046/49036134-2660fe00-f1b7-11e8-81d9-7468447e2e10.png)
![ambusher_shadow_min-fs8](https://user-images.githubusercontent.com/6249046/49036135-2660fe00-f1b7-11e8-98b1-156162485227.png)

**Comment by xR3b0rn** [comment]
I have made a layout for the new json to cover all data needed for animating units:
`{
	"images":
	[
		"assassin_shadow.png",
		"assassin_color.png",
		"assassin_base.png"
	]
	"sound":
	[
		"1_win.wav.mp3",
		"2_turnstart.wav.mp3"
	]
	"frames":
	{
		"down":
		{
			"move":
			[
				[
					{
						"sound":
						[
							{
								"i": 0
							}
							{
								"i": 1
							}
						]
						"spritesheet_data":
						[
							{
								"i": 0,
								"ox": -5,
								"oy": -5,
								"vx": 57,
								"vy": 58,
								"vw": 100,
								"vh": 100,
							},
							{
								"i": 1,
								"ox": -5,
								"oy": -5,
								"vx": 57,
								"vy": 58,
								"vw": 100,
								"vh": 100,
							},
							{
								"i": 2,
								"ox": -5,
								"oy": -5,
								"vx": 57,
								"vy": 58,
								"vw": 100,
								"vh": 100
							}
						]
					}
				]
			]
		}
	}
}
`

What do you think? is it blowing up or is any data missing?

**Comment by xR3b0rn** [comment]
Updated version due to arrangement with @pongstylin:
```
{
	"images":
	[
		"assassin_shadow.png",
		"assassin_color.png",
		"assassin_base.png"
	]
	"sound":
	[
		"1_win.wav.mp3",
		"2_turnstart.wav.mp3"
	]
	"frames":
	[
		{
			"sound": [0, 1]
			"frame":
			[
				{
					"i": 0,
					"x": -5,
					"y": -5,
					"vx": 57,
					"vy": 58,
					"vw": 100,
					"vh": 100,
				},
				{
					"i": 1,
					"x": -5,
					"y": -5,
					"vx": 57,
					"vy": 58,
					"vw": 100,
					"vh": 100,
				},
				{
					"i": 2,
					"x": -5,
					"y": -5,
					"vx": 57,
					"vy": 58,
					"vw": 100,
					"vh": 100
				}
			]
		}
	},
	"actions":
	{
		"move":
		{
			"S":
			{
				"start": 1
				"end": 10
			}
		}
	}
}

```

**Comment by pongstylin** [comment]
The assassin is a great example.  It is more complex than the Ambusher and it is a unit that I have already implemented, so I am very familiar with the data.  Please change your Assassin sample in these ways:
# Please add the rest of the data.  It appears the frames only have one layer.  I want to see how you handle the orange bomb explosion.
# Please omit the frame "sound" array if it is empty.
# This "actions" format is not easy to use, but keep it the same in the next sample.  I need to study this data more.
# The "sounds" array names need to match files in this directory.  While I am willing to rename the files in that directory, I prefer names that do not have spaces or symbols.
http://www.taorankings.com/html5/sounds/

**Comment by xR3b0rn** [comment]
1. I did and edited before you wrote
2. I will
3. it's the orginal
4. so the sounds have to be mapped, there have to be a mapping file

**Comment by xR3b0rn** [comment]
the new file:
https://nopaste.xyz/?e8d8b6bc2987bd2c#X2Pf76I7aI1RYVP/T29e2zvmyous7RYDbYPVuJBVPAs=

**Comment by pongstylin** [comment]
There still seems to be missing data.  Here is my JSON file for the assassin:
http://www.taorankings.com/html5/json/assassin.json

On frame #32, the assassin bomb begins.  It should have 4 layers.  You have 3 layers.  The 4th layer is a circle with an orange gradient.
On frame #34, the assassin becomes triplicate.  There is 1 shadow layer, 3 base layers, 3 color layers, and an orange explosion layer.

**Comment by xR3b0rn** [comment]
![assassin_base](https://user-images.githubusercontent.com/6249046/49093102-b52b5480-f263-11e8-83ba-d8d7b9a4de8a.png)

**Comment by pongstylin** [comment]
Ok, then I'll try running your JSON file on a webpage and see what I get.

**Comment by xR3b0rn** [comment]
[spritesheets.zip](https://github.com/pongstylin/tactics/files/2620912/spritesheets.zip)

**Comment by pongstylin** [comment]
@xR3b0rn 
I've created a new repository for you.
https://github.com/pongstylin/tactics_unit_testing

Please commit all of your resources to this repository and make sure they work well.  Once they do, I'll upload the resources to www.taorankings.com for use by the game.  Also, if you are feeling adventurous, feel free to modify the JavaScript and HTML files to improve the testing experience.

As for the assassin, it seems the shadow becomes out-of-sync from the rest of the layers.  Otherwise, I was pleased that it was as easy to center the animation on a specific tile as you said it would be.

**Comment by pongstylin** [comment]
Thanks for pushing all of your content into the new repository.  I did some review and would like to see a couple of changes to help me study the actions further.
# Please remove the "frame.reverse()".  It has a bug.  The reverse method changes the "frame".  So if you click on "t1" multiple times, you get different results.  In fact, the JSON data should be reversed.  So, please change the export so that the JSON "frame" array lists the layers in "shadow", "base", and "color" order.
# All of the actions that have more than one frame has an incorrect "end" index.  It is one digit too high.  Take the assassin for example.  "s1" should be "0-1".  "lpa1" should be "2-6".  "lpc1" should be "8-10".  "m1" should be "12-20".  "a1" should be "21-31".  Using the unit testing app, you can easily see that "m1" and "a2" ends at the wrong frame.  These numbers might be what you got from the XML, but I want it to be consistent with the single frame actions, which has the same number for "start" and "end".  In other words, I want "end" to consistently be the index OF the last frame, not the index AFTER the last frame.

**Comment by pongstylin** [comment]
@xR3b0rn 
I found a 3rd problem where the "Black Spike" animation could not be played, because the JSON data is expecting a larger black_spike_base.png image.  In other words, the image is 188 pixels wide, but the 3rd frame is trying to pull a sprite with this data: vx:176 + vw:36 = 212 > 188.

**Comment by pongstylin** [comment]
I'm closing out this issue.  I finally made headway in exporting data from the original game's SWF.  My technique includes sound data as well as some randomization data.  It doesn't use spritesheets, but does embed the sound and image files into JSON files using Data URIs.  Technically, spritesheets are more efficient when executing animations in the GPU, but that is an effort for another day, if it ever becomes a priority.
