### ISSUE TITLE
Server branch integration with game

### ISSUE THREAD

**Issue by Enijar** [pongstylin/tactics#15]
I've been working on the server branch getting things setup and ready to be reviewed for a merge into master. However the game doesn't load. I see this in the console:

```
Uncaught Error: Cannot add resources while the loader is running.
    at Loader.add (Loader.js:336)
    at classic-app.js:309
    at Array.forEach (<anonymous>)
    at load (classic-app.js:305)
    at classic-app.js:265
    at dispatch (jquery.min.js:3)
    at r.handle (jquery.min.js:3)
```

Steps to reproduce:

• Checkout to the server branch
• Run 
```
make install
cp env/server.example.json env/server.json
cp env/common.example.json env/common.json
make dev -j2
```
• Open [http://localhost:3000/play?mode=faceoff](http://localhost:3000/play?mode=faceoff)

**Comment by Enijar** [comment]
Great news!

**Comment by pongstylin** [comment]
Finally finished fixing the Chaos app.  It took a long time because I needed to figure out how to articulate the Chaos Seed and Chaos Dragon behavior so that it can be made into an abstract game mechanic.  The behavior is that the Chaos Seed and Chaos Dragon can sometimes respond to being attacked.  Responses can vary, but regardless of the response, I'm calling it a "Counter-Attack".  The original game had no units that is capable of a "Counter-Attack", but I'm considering this to be one way to enhance the "Berserker" unit so that won't be so ignored by pro players.
