### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by AitorG** [pongstylin/tactics#60]
Hello, I would like to know if the resources can be exported to local files. I would like to make a fully mobile version of the game and get better performance having all images of units locale saved. Anyway, if the domain that are published breaks, get down or dissapears, we lose the resources, and thats not good at all. I would like to have full control of those resources. Do you think thats possible?
thanks!

**Comment by pongstylin** [comment]
Right now there are hundreds of files... mostly images.  They are not included in the repository because they are not licensed.  With that said, there are some solutions.

First, many mobile games download resources from the web.  They can download updates without you updating the app in the app store.  But once the update is installed, it is all local.  This game is similar.  It uses Service Workers to cache resources locally.  The game can be played offline.  There is room for improvement, but it already offers the performance benefit you are looking for.

But then there is the concern about the resources being lost if my server is shut down.  While it is quite possible to download all hundreds of files from my server, it would suck.  I am still working to improve the form of the data so that resources are better consolidated and organized.  Once finished, there would only be one or two files per unit and maybe a couple dozen shared files.  That would be much more manageable for you.

Finally, the resources are not licensed.  The original creator may discover that his hard work is being used by other people without his permission.  He might choose to bring legal action.  It is my belief that this is unlikely and, if he does make himself known, I would try to buy ownership or license.  Even so, the safest path is to hire an artist to make new artwork and plug it into the game.  Besides, you would have to do this anyway if you intend to create new units.

**Comment by AitorG** [comment]
thanks a lot for the response. 
I'm starting creating a stable and complete server about the games, rooms, and those stuffs.
Then I'm gonna contact to my designers mates to make new resources for the game, I think. Anyway I'm still studing this code and thinking about things to improve, things to remake and things to add.

Thanks for sharing your job!

**Comment by pongstylin** [comment]
No problem.  If interested, I can give you a discord link or Facebook messenger link if you wish to discuss strategy or the details of how my code works.  I know it can be difficult to understand what a person was thinking when reading their code.

**Comment by AitorG** [comment]
Yes, I am really interested. Can you provide a Discord link?

**Comment by pongstylin** [comment]
Here you go.  My name in the chat is BrutalRage since that was my old TAO name.
https://discord.gg/y759su
