### ISSUE TITLE
Option for timed turns

### ISSUE THREAD

**Issue by theRJMurray** [pongstylin/tactics#65]
This would allow people to choose to play real-time (timer enabled) or over a long period (no timer)

**Comment by pongstylin** [comment]
Hello @theRJMurray and thanks for providing feedback!

The website included in this repository is intended to provide an example of how to launch the game.  I expect that people who fork this repository to create their own instance of the game will want to create their own site while still taking advantage of the underlying game engine.  As they do so, they can offer user-choice in what timers they may choose.  This is because the underlying game engine already supports configurable time limits.  The example website simply sets it to 7 days for all games.  Once the time limit is reached, the opponent has a choice of forcing surrender, or waiting longer.

I intend to fork my own repository to create a commercial service.  It will include a lobby where people can initiate a game while they are both online and, in that context, it makes sense to have a real-time time limit.  Since the example site does not have a lobby, I don't think real-time time limits make sense.  If you disagree and think the example site (and Playground server) should have configurable time limits, please explain how you think it would work.

**Comment by theRJMurray** [comment]
I understand now. I am just looking forward to the lobby feature and wasn't sure if I should be looking to this repository or another for this feature. Thanks!
