### ISSUE TITLE
Max Unit Count: Barrier Ward

### ISSUE THREAD

**Issue by Enijar** [pongstylin/tactics#68]
I just saw the merge for Legends Gray – looks perfect!

I noticed that there is a max of 10 Barrier Wards; is this how the old game worked? I'm just thinking that the Barrier Ward should have a max of lower than the current army count and should only be placed if there is another unit. The reason for this is that the Barrier Ward can protect itself meaning the game is a stalemate. Thoughts?

**Comment by pongstylin** [comment]
I set the limit to 9 per your suggestion.

The "if there is another unit" thing can be a little awkward.  Because then I would have to check if they delete that other unit and only wards remain.  It is simpler for the user and the developer to just have one check at the point you hit the save button.  If the only thing on the board is wards, then it will tell you to add a non-ward unit.  This is already in place.
